name: github pages
on:
  push:
    branches:
      - master
      - develop
jobs:
  deploy:
    runs-on: ubuntu-18.04
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm install gitbook
        run: |
         npm install -g gitbook-cli
         gitbook install
         gitbook build . docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BOOK_DEPLOY }}
          publish_dir: ./docs
          commit_message: ${{ github.event.head_commit.message }}
